// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dsOMYhhzTXFWRJDVBlidx7JO4z9REsg',
    appId: '1:1078204721197:web:44dc59646920630005b0a4',
    messagingSenderId: '1078204721197',
    projectId: 'task-3-44e83',
    authDomain: 'task-3-44e83.firebaseapp.com',
    storageBucket: 'task-3-44e83.appspot.com',
    measurementId: 'G-K5J33V73T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfyt3YcbuzniB53mDihJ1zXF1M_Sqpes',
    appId: '1:1078204721197:android:9f7f36a596c95c1b05b0a4',
    messagingSenderId: '1078204721197',
    projectId: 'task-3-44e83',
    storageBucket: 'task-3-44e83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKPnRyFc7Mw_IsrUSnq7bDAkuyODwiVS8',
    appId: '1:1078204721197:ios:41ff0f3d5da200df05b0a4',
    messagingSenderId: '1078204721197',
    projectId: 'task-3-44e83',
    storageBucket: 'task-3-44e83.appspot.com',
    iosBundleId: 'com.kawish.task3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKPnRyFc7Mw_IsrUSnq7bDAkuyODwiVS8',
    appId: '1:1078204721197:ios:41ff0f3d5da200df05b0a4',
    messagingSenderId: '1078204721197',
    projectId: 'task-3-44e83',
    storageBucket: 'task-3-44e83.appspot.com',
    iosBundleId: 'com.kawish.task3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-dsOMYhhzTXFWRJDVBlidx7JO4z9REsg',
    appId: '1:1078204721197:web:c924229c0a1763ef05b0a4',
    messagingSenderId: '1078204721197',
    projectId: 'task-3-44e83',
    authDomain: 'task-3-44e83.firebaseapp.com',
    storageBucket: 'task-3-44e83.appspot.com',
    measurementId: 'G-85062V93JT',
  );
}
